services:
  - type: web
    name: picpass-client
    env: static
    repo: https://github.com/yourusername/picpass-client
    branch: main
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://picpass-server.onrender.com

  - type: web
    name: picpass-server
    env: docker
    repo: https://github.com/yourusername/picpass-server
    branch: main
    dockerContext: .
    plan: free
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: TWILIO_SID
        value: your-twilio-sid
      - key: TWILIO_TOKEN
        value: your-twilio-token
      - key: TWILIO_PHONE
        value: your-twilio-phone
