services:
  # FRONTEND: React + Vite hosted with Express (Node.js)
  - type: web
    name: picpass-client
    env: node
    rootDir: client
    buildCommand: npm install && npm run build     # ✅ install dependencies first!
    startCommand: npm run start
    plan: free
    envVars:
      - key: VITE_API_BASE
        value: https://picpass-server.onrender.com

  # BACKEND: Spring Boot (Dockerized)
  - type: web
    name: picpass-server
    env: docker
    rootDir: server
    dockerContext: .
    plan: free
    envVars:
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: TWILIO_SID
        value: your-twilio-sid
      - key: TWILIO_TOKEN
        value: your-twilio-token
      - key: TWILIO_PHONE
        value: your-twilio-phone
